### ISSUE TITLE
LambdaElse evaluated even if condition is true

### ISSUE THREAD

**Issue by SapphireBrand** [polterguy/lizzie#10]
The implementation of Functions.If will evaluate both lambdaIf and lambdaElse even if condition is != null. That is, it does the validation and sanity checking even if one of the lambdas is not needed.

This is not a bug necessarily. But it seems to me to be more in the spirit of the language that things are only validated if they are used. So if it were my code, the I would write If as follows:

```
public static Function<TContext> If => new Function<TContext>((ctx, binder, arguments) =>
{
    // Sanity checking code.
    if (arguments.Count < 2)
        throw new LizzieRuntimeException("The 'if' keyword requires at least 2 arguments, and you tried to invoke it with fewer.");

    // Retrieving condition, if(true) lambda, and sanity checking invocation.
    var condition = arguments.Get(0);
    if (condition != null)
    {
        var lambdaIf = arguments.Get(1) as Function<TContext>;
        if (lambdaIf == null)
            throw new LizzieRuntimeException("The 'if' keyword requires a lambda argument as its second argument.");
        return lambdaIf(ctx, binder, arguments);
    }

    // Execute the else-clause, if one is present:
    if (arguments.Count > 2)
    {
        var lambdaElse = arguments.Get(2) as Function<TContext>;
        if (lambdaElse == null)
            throw new LizzieRuntimeException("The 'if' keyword requires a lambda argument as its third (else) argument if you supply a third argument.");
        return lambdaElse(ctx, binder, arguments);
    }

    // If yields false, and there is no "else lambda".
    return null;
});
```

**Comment by polterguy** [comment]
Hmm, thank you very much :)

I'll have a deeper look at this in the upcoming weekend, and if it passes all tests and seems logical once I've get to burn some neurons on it, I'll apply it to the lib. Thank you!

Keep the good suggestions coming :)

**Comment by polterguy** [comment]
They're all stored here, I just need to find time to sit down and actually do them (I'm working 9 hours 5 days a week, and I commute 2 hours every day, so I don't get to really apply any cognitive energy on Lizzie besides ever now and then in the weekends ...)

**Comment by polterguy** [comment]
Fixed in repo.
