### ISSUE TITLE
Slice should allow a zero-length result

### ISSUE THREAD

**Issue by SapphireBrand** [polterguy/lizzie#14]
Functions.Slice throws an exception if end == start, but those would not ne invalid arguments to the AddRange call that follows. Returning an empty section of a list is a valuable option that would often avoid pointless tests outside of the slice call.

**Comment by polterguy** [comment]
Hmm, valid point!

**Comment by polterguy** [comment]
Fixed in repo! We can now perform a `slice` returning _"no-slice"_ :D

Sorry, I love _"word poetry"_ ... ;)
