### ISSUE TITLE
Inconsistent error message in Json function

### ISSUE THREAD

**Issue by SapphireBrand** [polterguy/lizzie#18]
The exception message in Functions.Json refers to the 'object' function, but "Json" is the name bound in LambdaCompiler<>.

**Comment by polterguy** [comment]
Holy macaroni man, you're on fire :D

Hey, if you'd like to send me a couple of patches, and they're good, I might as well provide you with write access to the repo ...?

I'd appreciate if you write tests covering whatever you do. I'm not too fascist about code quality on the tests, but the core must be according to current coding standards ...

Interested ...?

I'll need a public official statement of that you're OK with that your code is licensed under the terms of the MIT license though (a single sentence here will suffice) ...

**Comment by polterguy** [comment]
Fixed! (in repo)
