### ISSUE TITLE
Awesome!

### ISSUE THREAD

**Issue by spadino** [polterguy/lizzie#2]
Hi! Lizzie really got my attention. I was searching for a scripting solution for some projects and, being a lisp lover, I considered code my own lisp. How delighted I became when I found Lizzie! Terrific work!!!
Although, I'm not a professional coder, and I'm still learning many aspects of c#. I would love to know if it's possible to get some help from you for my current project: I'm prototyping an open source generic scripted engine to remap and program input/output devices, such as joysticks, mice, keyboard, etc... is it possible to implement a kind of REPL for Lizzie, or a simple life code evaluator? I found that could be help for casual coders which would like to contribute to understand better how to interact with the DSL language and syntax I'll extend from Lizzie. If you have any advice of if you can point me to the right direction I'll be extremely grateful.

Thanks for the awesome Lizzie!

**Comment by polterguy** [comment]
Thx for the nice words :)

With REPL I assume you mean some sort of code editor, that allows you to type in code, and have it immediately evaluated by clicking a button, right? I've already created one of these, although the one I created was for the web. You can [see it here](https://dzone.com/articles/full-stack-development-from-client-side-javascript). Creating something similar for desktop should be easy by following the same recipe. I've also got a [YouTube video demonstrating using VS Code](https://www.youtube.com/watch?v=civu_pnmpU0) in a similar way using a console app as my _"REPL evaluator"_.

Hopefully this should get you started :)

**Comment by polterguy** [comment]
Thx :)

Psst, I got curious about your profile image, so I checked up your website. You're an inspiring guy yourself I must confess. FYI, I play several instruments myself (hobbyist though) - Guitar, drums, saxophone ++.

**Comment by spadino** [comment]
That's pretty awesome! They are very different instruments, so definitely they are able to give you a broad understanding of the musical language. I'm glad to had met you!

All the best! And let stay in touch

BTW, I'm quite flattered by your consideration... ;) I share the same feeling for you and your work.
