### ISSUE TITLE
Exceptions thrown in parsing numbers

### ISSUE THREAD

**Issue by SapphireBrand** [polterguy/lizzie#23]
Compiler.CompileNumber uses double.Parse and long.Parse, which will thrown ArgumentNullException , FormatException, or OverflowException. (https://docs.microsoft.com/en-us/dotnet/api/system.double.parse?redirectedfrom=MSDN&view=netframework-4.7.2#System_Double_Parse_System_String_)

I think better is to TryParse(), and then thrown your own exception. This will allow programs that call Lizzie to trap execution issues better.

**Comment by polterguy** [comment]
Hmm, yet again the exception issue. This one is more easy to agree with by default I think ...

**Comment by polterguy** [comment]
Fixed (in repo)!
