### ISSUE TITLE
IsNumeric and negatives

### ISSUE THREAD

**Issue by SapphireBrand** [polterguy/lizzie#25]
So we need a way to have "-17" be a valid number.

I think the simplest is to allow IsNumeric to accept a leading minus sign. (That is, I don't think there are any potential confusions in lexing/parsing regarding minus signs. But maybe I missed something.)

Some languages support -17 using "unary minus" (AKA negation). But that would be awkward in Lizzie syntax, because unary minus would have parentheses: "-(17)". (Separate issue is filed requesting unary minus support.)

**Comment by polterguy** [comment]
I agree, `-17` should be understood as negative 17 ...

**Comment by polterguy** [comment]
Fixed (in repo)!
