### ISSUE TITLE
Unary minus

### ISSUE THREAD

**Issue by SapphireBrand** [polterguy/lizzie#26]
Should have a function for negation. The alternative of coding -(0, 17) is possible, but seems...like a workaround for an obvious shortcoming.

**Comment by polterguy** [comment]
I think your scenario could be done by making sure `-17` is parsed as a numeric ...

**Comment by SapphireBrand** [comment]
Parsing negative numbers would cover one case.

Additionally, there is no way to say "-@variable", unless you write "-(0, @variable)"

**Comment by polterguy** [comment]
Well, its nature is that everything is a function. I see how it becomes unintuitive that you'd have to use 0, -x. Maybe change it such that it allows for -(x) ...

**Comment by polterguy** [comment]
Fixed in repo, now it allows for the following ...

```
var(@foo,10)
-(foo)
```
