### ISSUE TITLE
Duplicated tests in LambdaBuilder

### ISSUE THREAD

**Issue by SapphireBrand** [polterguy/lizzie#33]
The tests named `WithType` and `WithoutType` in `LambdaBuilder` are identical.

**Comment by polterguy** [comment]
Thank you for you careful eyes, I'll look into all 4 of these hopefully over the next weekend :)

Unless you want to provide me with a patch ...?

**Comment by SapphireBrand** [comment]
I am finding a lot of issues because I am porting Lizzie to TypeScript, which means I get to check every line of code. When I have something working then I will open source it here on GitHub.

Alas, this won't leave me a lot of time for pull requests here. But I will continue to post issues. :-)

**Comment by polterguy** [comment]
Fixed!
