### ISSUE TITLE
AddValue return value policies are inconsistent

### ISSUE THREAD

**Issue by SapphireBrand** [polterguy/lizzie#34]
The implementation of AddValue in the case where arguments.Get(0) is a list will modify each the list by appending each element, and then return the last element added.

If arguments.Get(0) is a dictionary, then it returns a count of the size of the map after all additions have been made.

So I would think that the obvious thing to return is the first object, to facilitate chaining of operations. That is, if you just built up a list or map, then you probably want to do something with it.

Are there use cases for the current policies?

**Comment by polterguy** [comment]
Actually, in the GIT repository it actually returns the last value if the first object is a Dictionary. I just haven't created a release of it quite yet. In fact, if I am not entirely wrong, I think this was implemented according to your wishes some time back ago.

(Not to self) - Create a new Release on Sunday, or during the weekend ... ;)
