### ISSUE TITLE
Return value of Each()

### ISSUE THREAD

**Issue by SapphireBrand** [polterguy/lizzie#35]
The Each function returns the original list to the caller, which is not very functional because the caller passed it in.

A much more useful return value would be the values returned by the lambda functions. It is telling that all of the `each` test cases declare a variable which will be used to accumulate the lambda values.

**Comment by polterguy** [comment]
Actually, in its current version, which is _not yet released though_, it is actually returning the value of the `each` lambda, allowing for transformations and such of lists.

Sorry for not having made a release of this yet though. I'll spend some time this weekend, and get a new release out the door ...
