### ISSUE TITLE
Why doesn't Apply take a function and a list?

### ISSUE THREAD

**Issue by SapphireBrand** [polterguy/lizzie#36]
The syntax for `apply` is `+(apply(list(57,10,10))` where I would have expected `apply(+, list(57,10,10))`.

The actual definition of apply requires a peculiar special case in the ApplyArguments execution, whereas if we define apply as a function then we can put that logic in the place it belongs.

**Comment by polterguy** [comment]
Hmm, that is a very relevant question, and your suggestion is probably better in fact I must confess. Unfortunately it would break too much existing code out there to change now, and the _"inconvenience"_ of having to put the function invocation outside doesn't justify such a breaking change ...
