### ISSUE TITLE
Unit tests for non-terminated string and newline-in-string

### ISSUE THREAD

**Issue by SapphireBrand** [polterguy/lizzie#43]
I wrote two tests because of a code review of the TypeScript Lizzie, as below.

    it('NonTerminatedString', () => {
        var code = "'non terminated string";
        var tokenizer = new Tokenizer(new LizzieTokenizer());
        let thrown = true;
        try {
            var list = tokenizer.tokenizeString(code);
            thrown = false;
         } catch (e) {
            expect(e.error).toMatch(/.*Syntax error, string literal not closed.*/i);
        }
        expect(thrown).toBe(true);
    });

    it('NewlineInString', () => {
        var code = "'string with \n newline";
        var tokenizer = new Tokenizer(new LizzieTokenizer());
        let thrown = true;
        try {
            var list = tokenizer.tokenizeString(code);
            thrown = false;
         } catch (e) {
            expect(e.error).toMatch(/.*Syntax error, string literal contains CR or LF.*/i);
        }
        expect(thrown).toBe(true);
    });

**Comment by polterguy** [comment]
Thank you, I created some similar tests in my own code. They passed for the record, without any changes to Lizzie.
