### ISSUE TITLE
I think that it would be a good idea for devs!

### ISSUE THREAD

**Issue by RpxdYTX** [polterguy/lizzie#50]
Hi polterguy, sorry for being inconvenient and asking this to you, but i found your discovery very interesting and powerful, but could you add extra docs for explaining (in details) what everything does? I tried replicating lizzie for educational purposes, but using my own code and i found that it is kinda hard to understand what everything do just by seeing its code so i decided to ask if that extra docs are possible, nevermind if i am being too exigent or if i'm asking something very hard, but thanks for sharing with us this wonderful and simple method of language creation that i dare cal it "Symbolization" for shorting the S-exp or Symbolic Delegates, and if you are going to do it, take your time, without pressures. Again thanks.

**Comment by polterguy** [comment]
Howdy, to be honest with you I haven't touched Lizzie for a very long time, and I don't imagine myself touching it again unfortunately. My current _"baby"_ is [Magic](https://polterguy.github.io), which I spend all my time working on ...

**Comment by RpxdYTX** [comment]
Ok, thank you anyway
