### ISSUE TITLE
Escape quote

### ISSUE THREAD

**Issue by SapphireBrand** [polterguy/lizzie#7]
The tokenizer should recognize \" as a quote character within a string.

**Comment by SapphireBrand** [comment]
Never mind; the code matches the stop character. So this is supported.

**Comment by polterguy** [comment]
Hehe, you can use all of these ...

```
"foo"
```

```
'foo'
```

```
@"foo"
```

And they match the expectations a C# developer would have, so I think you should be pretty well covered ... :)
