### ISSUE TITLE
PopStack on wrong Binder

### ISSUE THREAD

**Issue by SapphireBrand** [polterguy/lizzie#9]
In Functions.Function, the code calls binder2.PushStack but binder.PopStack. The PopStack call should be on binder2.

I think unit tests would not catch this because the same binder is used throughout. You might want to get a different binder into some test.

**Comment by polterguy** [comment]
Ouch! If you've got some suggestions for patching this, I'd appreciate it. Preferably with a test that doesn't pass before the patch is applied ...

Thank you yet again :)

**Comment by polterguy** [comment]
Fixed in repo, although I doubt the binder would ever be different, since the binder is basically the same for all functions unless you do something very special ...
